FROM python:3.12

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir kafka-python

RUN pip install kafka-python requests

RUN pip install pandas

COPY trades.csv /app/

CMD ["python", "consumer.py"]